"use client";

import { useEffect, useState, useSyncExternalStore } from "react";
import { Loader2, Pause, Play, SkipBack, SkipForward, Volume2, X } from "lucide-react";
import { SPEECH_RATES, speechStore, useSpeech, type SpeechVoiceInfo } from "@/lib/speech-store";
import type { Message } from "@/lib/types";
import { Button } from "./ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select";

const NO_VOICES: SpeechVoiceInfo = { provider: null, voices: [], defaultVoice: null };

export function ListenButton({ message }: { message: Message }) {
  const speech = useSpeech();
  const active = speech.messageId === message.id && speech.status !== "idle";
  const busy = active && (speech.status === "playing" || speech.status === "loading");
  const label = busy ? "Pause reading" : active ? "Resume reading" : "Read aloud";
  return (
    <Button type="button" variant="ghost" size="icon" className={`listen-button${active ? " is-active" : ""}`} aria-label={label} title={label} aria-pressed={active}
      onClick={() => speechStore.toggle(message)}>
      {busy ? <Pause /> : <Volume2 />}
    </Button>
  );
}

function formatRate(rate: number) {
  return `${rate}×`;
}

/**
 * Compact transport for the message being read. Rendered inside that message so the controls stay next to
 * the highlighted passage; the store keeps playing if the component unmounts (e.g. switching chats).
 */
export function SpeechPlayer({ messageId }: { messageId: string }) {
  const speech = useSpeech();
  const [info, setInfo] = useState<SpeechVoiceInfo>(NO_VOICES);
  useEffect(() => {
    let cancelled = false;
    void speechStore.voiceInfo().then((value) => { if (!cancelled) setInfo(value); });
    return () => { cancelled = true; };
  }, []);
  if (speech.messageId !== messageId || speech.status === "idle") return null;
  const total = speech.chunks.length;
  const playing = speech.status === "playing" || speech.status === "loading";
  const voice = info.voices.some((entry) => entry.id === speech.voice) ? speech.voice! : info.defaultVoice ?? "";
  return (
    <div className="speech-player" role="region" aria-label="Read aloud" data-status={speech.status}>
      <Button type="button" variant="ghost" size="icon" aria-label="Previous passage" title="Previous passage" disabled={speech.chunk === 0} onClick={() => speechStore.previous()}><SkipBack /></Button>
      <Button type="button" variant="secondary" size="icon" className="speech-toggle" aria-label={playing ? "Pause" : "Play"} title={playing ? "Pause" : "Play"}
        onClick={() => (playing ? speechStore.pause() : speechStore.resume())}>
        {speech.status === "loading" ? <Loader2 className="speech-spinner" /> : playing ? <Pause /> : <Play />}
      </Button>
      <Button type="button" variant="ghost" size="icon" aria-label="Next passage" title="Next passage" disabled={speech.chunk + 1 >= total} onClick={() => speechStore.next()}><SkipForward /></Button>
      <span className="speech-progress" aria-live="polite">
        {speech.status === "error" ? <span className="speech-error">{speech.error}</span> : <>Passage {speech.chunk + 1} of {total}</>}
      </span>
      <Select value={String(speech.rate)} onValueChange={(value) => speechStore.setRate(Number(value))}>
        <SelectTrigger aria-label="Reading speed" className="speech-pill"><SelectValue>{formatRate(speech.rate)}</SelectValue></SelectTrigger>
        <SelectContent>{SPEECH_RATES.map((rate) => <SelectItem key={rate} value={String(rate)}>{formatRate(rate)}</SelectItem>)}</SelectContent>
      </Select>
      {info.voices.length > 1 && (
        <Select value={voice} onValueChange={(value) => speechStore.setVoice(value)}>
          <SelectTrigger aria-label="Voice" className="speech-pill"><SelectValue>{info.voices.find((entry) => entry.id === voice)?.label ?? "Voice"}</SelectValue></SelectTrigger>
          <SelectContent>{info.voices.map((entry) => <SelectItem key={entry.id} value={entry.id}>{entry.label}</SelectItem>)}</SelectContent>
        </Select>
      )}
      <span className="speech-disclosure" title="This voice is generated by an AI text-to-speech model.">AI voice</span>
      <Button type="button" variant="ghost" size="icon" aria-label="Stop reading" title="Stop reading" onClick={() => speechStore.stop()}><X /></Button>
    </div>
  );
}

/** Marks the blocks of `root` whose source range overlaps the passage being read. */
export function useSpeechHighlight(root: React.RefObject<HTMLElement | null>, messageId: string) {
  // A primitive snapshot keeps idle messages from re-rendering on every playback state change.
  const range = useSyncExternalStore(speechStore.subscribe, () => {
    const speech = speechStore.getSnapshot();
    const current = speech.messageId === messageId && speech.status !== "idle" && speech.status !== "error" ? speech.chunks[speech.chunk] : null;
    return current ? `${current.start}:${current.end}` : "";
  }, () => "");
  const [start, end] = range ? range.split(":").map(Number) : [-1, -1];
  useEffect(() => {
    const container = root.current;
    if (!container || start < 0) return;
    const blocks = new Set<HTMLElement>();
    for (const leaf of container.querySelectorAll<HTMLElement>("[data-md-start]")) {
      const leafStart = Number(leaf.dataset.mdStart);
      const leafEnd = Number(leaf.dataset.mdEnd);
      if (leafEnd <= start || leafStart >= end) continue;
      const block = leaf.closest<HTMLElement>(".markdown > *, .markdown li") ?? leaf;
      blocks.add(block);
    }
    for (const block of blocks) block.classList.add("speech-current");
    const first = blocks.values().next().value;
    first?.scrollIntoView({ block: "nearest", behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "instant" : "smooth" });
    return () => { for (const block of blocks) block.classList.remove("speech-current"); };
  }, [root, start, end]);
}
